CONFIG = {
    "BOT_TOKEN": "YOUR_DEV_DISCORD_BOT_TOKEN",
    "DATABASE_URL": "YOUR_DEV_DATABASE_CONNECTION_STRING",
    "YOUTUBE_API_KEY": "YOUR_DEV_YOUTUBE_API_KEY",
    "SPOTIFY_CLIENT_ID": "YOUR_DEV_SPOTIFY_CLIENT_ID",
    "SPOTIFY_CLIENT_SECRET": "YOUR_DEV_SPOTIFY_CLIENT_SECRET"
}
